# Generated by Django 2.1.5 on 2019-02-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('lastdate', models.DateField(null=True)),
                ('salary', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('requirements', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cv', models.FileField(upload_to='img/file')),
                ('moreinfo', models.CharField(max_length=2000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Career')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='img')),
                ('course', models.CharField(max_length=500)),
                ('seats', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('details', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='img')),
                ('event', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Departments'),
        ),
    ]
